# This is the provider confiuration; it is told to use aws from the terraform.tf file
provider "aws" {
  # This sets the region to be used in AWS
  region = "us-east-1"
}

# This resource creates the S3 bucket with terraform autogenerating the name it has not name given
resource "aws_s3_bucket" "label_bucket" {
  # When destroying this will force all items inside the bucket to be deleted, thereby avoiding errors
  force_destroy = true
}

# This resource established an object to be stored in the S3 Bucket
resource "aws_s3_object" "street_view" {
  # This is where the object will be stored; I used aws_s3_bucket.label_bucket.id since the bucket's name is autogenerated
  bucket = aws_s3_bucket.label_bucket.id
  # The object uploaded will be given this name
  key = "busy_street.jpg"
  # the object'r original name and location; it is in the same folder as the terraform files
  source = "city_street.jpg"
}

# This is the output that will be expose the bucket's name for the python script; must run $env:BUCKET_NAME = terraform output -raw existing_s3_bucket in powershell after apply command
output "existing_s3_bucket" {
  description = "This is the name of the bucket for use in python script"
  value       = aws_s3_bucket.label_bucket.id
}